### fibonacci

runtime complexity is given by $O(2n)$

In [1]:
def fibonacci(n):
  """
  Returns the n-th number in the Fibonacci sequence.
  Parameters
  ----------
  n: int
  The n-th number in the Fibonacci sequence.
  """
  if n <= 1:
    return n
  else:
    return fibonacci(n-1) + fibonacci(n-2)

In [2]:
fibonacci(5)

5

In [3]:
fibonacci(4) + fibonacci(3)

5

In [4]:
fibonacci(5) == fibonacci(4) + fibonacci(3)

True

In [5]:
fibonacci(5) == ((fibonacci(2) + fibonacci(1)) + (fibonacci(1) + fibonacci(0))) + ((fibonacci(1) + fibonacci(0)) + fibonacci(1))

True

In [6]:
fibonacci(5) == (((fibonacci(1) + fibonacci(0)) + fibonacci(1)) + (fibonacci(1) + fibonacci(0))) + ((fibonacci(1) + fibonacci(0)) + fibonacci(1))

True

### fibonacci dictionary

 runtime complexity of this algorithm is $O(n)$

In [7]:
cache = {0: 0, 1: 1} # Initialize the first two values.
def fibonacci(n):
  """
  Returns the n-th number in the Fibonacci sequence.
  Parameters
  ----------
  n: int
  The n-th number in the Fibonacci sequence.
  """
  try:
    return cache[n]
  except KeyError:
    fib = fibonacci(n-1) + fibonacci(n-2)
    cache[n] = fib 
    return fib

In [8]:
fibonacci(5)

5

In [9]:
fibonacci(4)

3

### fibonacci list

In [10]:
cache = [0, 1]   # Initialize with the first two terms of Fibonacci series.
def fibonacci(n):
  """
  Returns the n-th number in the Fibonacci sequence.
  Parameters
  ----------
  n: int
  The n-th number in the Fibonacci sequence.
  """
  for i in range(2, n):
    cache.append(cache[i-1] + cache[i-2])
  return cache[-1]

In [11]:
fibonacci(5) == fibonacci(4) + fibonacci(3)

True

### forward algorithm

 * computes the joint distribution of the position at any time instance using the output at that time instance
 * Forward algorithm: P(Zk, X1:k)
 * splits the joint distribution term into smaller known terms with variable, $Z_{k-1}$, in the distribution, $P(Z_k, X_{1:k})$, as follows: $ P(Z_k, X_{1:k}) = \sum^m_{z_{k-1=1}} P(Z_k, Z_{k-1}, X_{1:k} )  $

In [12]:
import numpy as np

transition_matrix = np.array(
             [[0.33, 0.33,    0,    0,    0, 0.33,    0,    0,    0,    0,    0,    0,    0],
              [0.33, 0.33, 0.33,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
              [   0, 0.25, 0.25, 0.25,    0,    0, 0.25,    0,    0,    0,    0,    0,    0],
              [   0,    0, 0.33, 0.33, 0.33,    0,    0,    0,    0,    0,    0,    0,    0],
              [   0,    0,    0, 0.33, 0.33,    0,    0, 0.33,    0,    0,    0,    0,    0],
              [0.33,    0,    0,    0,    0, 0.33,    0,    0, 0.33,    0,    0,    0,    0],
              [   0,    0, 0.33,    0,    0,    0, 0.33,    0,    0,    0, 0.33,    0,    0],
              [   0,    0,    0,    0, 0.33,    0,    0, 0.33,    0,    0,    0,    0, 0.33],
              [   0,    0,    0,    0,    0, 0.33,    0,    0, 0.33, 0.33,    0,    0,    0],
              [   0,    0,    0,    0,    0,    0,    0,    0, 0.33, 0.33, 0.33,    0,    0],
              [   0,    0,    0,    0,    0,    0,    0,    0,    0, 0.33, 0.33, 0.33,    0],
              [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 0.33, 0.33, 0.33],
              [   0,    0,    0,    0,    0,    0,    0, 0.33,    0,    0,    0, 0.33, 0.33]])

emission = np.array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0])

init_prob = np.array([0.077, 0.077, 0.077, 0.077, 0.077, 0.077, 0.077,
                      0.077, 0.077, 0.077, 0.077, 0.077, 0.077])

def forward(obs, transition, emission, init):
    """
    Runs forward algorithm on the HMM.
    Parameters
    ----------
    obs:        1D list, array-like
                The list of observed states.
    transition: 2D array-like
                The transition probability of the HMM.
                size = {n_states x n_states}
    emission:   1D array-like
                The emission probabiltiy of the HMM.
                size = {n_states}
    init:       1D array-like
                The initial probability of HMM.
                size = {n_states}
    Returns
    -------
    float: Probability value for the obs to occur.
    """
    n_states = transition.shape[0]
    fwd = [{}]

    for i in range(n_states):
        fwd[0][y] = init[i] * emission[obs[0]]
    for t in range(1, len(obs)):
        fwd.append({})
        for i in range(n_states):
            fwd[t][i] = sum((fwd[t-1][y0] * transition[y0][i] * emission[obs[t]]) for y0 in 
                                    range(n_states))
    prob = sum((fwd[len(obs) - 1][s]) for s in range(n_states))
    return prob

In [13]:
emission = np.array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0])

initial probability, $P(Z_0)$, can be written as follows:

In [14]:
init_prob = np.array([0.077, 0.077, 0.077, 0.077, 0.077, 0.077, 0.077,
                      0.077, 0.077, 0.077, 0.077, 0.077, 0.077])

In [15]:
obs = [0, 0, 0, 0] # Staying in the same location

In [ ]:
forward(obs, transition_matrix, emission, init_prob)

### backward algorithm

In [17]:
def backward(obs, transition, emission, init):
    """
    Runs backward algorithm on the HMM.
    Parameters
    ----------
    obs:        1D list, array-like
                The list of observed states.
    transition: 2D array-like
                The transition probability of the HMM.
                size = {n_states x n_states}
    emission:   1D array-like
                The emission probabiltiy of the HMM.
                size = {n_states}
    init:       1D array-like
                The initial probability of HMM.
                size = {n_states}
    Returns
    -------
    float: Probability value for the obs to occur.
    """
    n_states = transition.shape[0]
    bkw = [{} for t in range(len(obs))]
    T = len(obs)
    
    for y in range(n_states):
        bkw[T-1][y] = 1
    for t in reversed(range(T-1)):
        for y in range(n_states):
            bkw[t][y] = sum((bkw[t+1][y1] * transition[y][y1] * emission[obs[t+1]]) for y1 in 
                                    range(n_states))
    prob = sum((init[y] * emission[obs[0]] * bkw[0][y]) for y in range(n_states))
    return prob

In [18]:
obs = [0, 0, 0, 0] # Staying in the same location

In [19]:
backward(obs, transition_matrix, emission, init_prob)

0.9738177680000003

In [20]:
obs = [0, 10, 8, 6] # Should be 0 because can't jump from state 0 to 10.

In [21]:
backward(obs, transition_matrix, emission, init_prob)

0.0

### The Viterbi algorithm

In [22]:
import numpy as np

In [23]:
def viterbi(obs, transition, emission, init=None):
    """
    Return the MAP estimate of state trajectory of Hidden Markov Model.
    Parameters
    ----------
    y : array (T,)
        Observation state sequence. int dtype.
    transition : array (K, K)
        State transition matrix. See HiddenMarkovModel.state_transition for
        details.
    emission : array (K,)
        Emission matrix. See HiddenMarkovModel.emission for details.
    init: optional, (K,)
        Initial state probabilities: Pi[i] is the probability x[0] == i. If
        None, uniform initial distribution is assumed (Pi[:] == 1/K).
    Returns
    -------
    x : array (T,)
        Maximum a posteriori probability estimate of hidden state trajectory,
        conditioned on observation sequence y under the model parameters.
    T1: array (K, T)
        the probability of the most likely path so far
    T2: array (K, T)
        the x_j-1 of the most likely path so far
    """
    # Cardinality of the state space
    K = transition.shape[0]

    emission = np.repeat(emission[np.newaxis, :], K, axis=0)

    # Initialize the priors with default (uniform dist) if not given by caller
    init = init if init is not None else np.full(K, 1 / K)
    T = len(obs)
    T1 = np.empty((K, T), 'd')
    T2 = np.empty((K, T), 'B')

    # Initilaize the tracking tables from first observation
    T1[:, 0] = init * emission[:, obs[0]]
    T2[:, 0] = 0

    # Iterate through the observations updating the tracking tables
    for i in range(1, T):
        T1[:, i] = np.max(T1[:, i - 1] * transition.T * emission[np.newaxis, :, obs[i]].T, 1)
        T2[:, i] = np.argmax(T1[:, i - 1] * transition.T, 1)

    # Build the output, optimal model trajectory
    x = np.empty(T, 'B')
    x[-1] = np.argmax(T1[:, T - 1])
    for i in reversed(range(1, T)):
        x[i - 1] = T2[x[i], i]

    return x, T1, T2

In [24]:
x, T1, T2 = viterbi([0, 0, 0, 0], transition_matrix, emission, init_prob)

In [25]:
print(x)

[0 0 0 0]


In [26]:
print(T1)

[[0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]
 [0.077      0.02541    0.0083853  0.00276715]]


In [27]:
print(T2)

[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  1  1  1]
 [ 0  3  3  3]
 [ 0  3  3  3]
 [ 0  0  0  0]
 [ 0  6  6  6]
 [ 0  4  4  4]
 [ 0  5  5  5]
 [ 0  8  8  8]
 [ 0  6  6  6]
 [ 0 10 10 10]
 [ 0  7  7  7]]


In [28]:
x, T1, T2 = viterbi([0, 10, 8, 6], transition_matrix, emission, init_prob)

In [29]:
print(x)

[0 0 0 0]


In [30]:
print(T1)

[[0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]
 [0.077 0.    0.    0.   ]]


In [31]:
print(T2)

[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  1  0  0]
 [ 0  3  0  0]
 [ 0  3  0  0]
 [ 0  0  0  0]
 [ 0  6  0  0]
 [ 0  4  0  0]
 [ 0  5  0  0]
 [ 0  8  0  0]
 [ 0  6  0  0]
 [ 0 10  0  0]
 [ 0  7  0  0]]
